/**
 * BhuMitra — Deterministic Master Demonstration Dataset
 * Smart India Hackathon 2026 — Problem Statement 26016
 *
 * Fully relational seed data:
 * - 6 States & Districts
 * - Official Officer Presets matching the frontend login
 * - 6 Flagship Projects
 * - Cadastral Land Parcels matching GIS Section & Parcel 360
 * - Valuations, 100% Solatium, Compensation Awards & DBT Disbursals
 * - R&R Resettlement Cases & Entitlements
 * - Grievance Cases & Statutory Section 15 Objections
 * - Field Inspection Verifications & GPS Geotagged Evidence
 * - Priority Action Centre Items with Live SLA Timelines
 */

export const SEED_STATES = [
  { id: 'state-gj', code: 'GJ', name: 'Gujarat', lgdCode: 24 },
  { id: 'state-mh', code: 'MH', name: 'Maharashtra', lgdCode: 27 },
  { id: 'state-rj', code: 'RJ', name: 'Rajasthan', lgdCode: 8 },
  { id: 'state-up', code: 'UP', name: 'Uttar Pradesh', lgdCode: 9 },
  { id: 'state-mp', code: 'MP', name: 'Madhya Pradesh', lgdCode: 23 },
  { id: 'state-od', code: 'OD', name: 'Odisha', lgdCode: 21 },
];

export const SEED_DISTRICTS = [
  { id: 'dist-vadodara', stateId: 'state-gj', name: 'Vadodara', code: 'VD', lgdCode: 450 },
  { id: 'dist-bharuch', stateId: 'state-gj', name: 'Bharuch', code: 'BH', lgdCode: 451 },
  { id: 'dist-ahmedabad', stateId: 'state-gj', name: 'Ahmedabad', code: 'AH', lgdCode: 452 },
  { id: 'dist-pune', stateId: 'state-mh', name: 'Pune', code: 'PN', lgdCode: 521 },
  { id: 'dist-nashik', stateId: 'state-mh', name: 'Nashik', code: 'NS', lgdCode: 522 },
  { id: 'dist-jaipur', stateId: 'state-rj', name: 'Jaipur Rural', code: 'JP', lgdCode: 104 },
  { id: 'dist-lucknow', stateId: 'state-up', name: 'Lucknow', code: 'LK', lgdCode: 157 },
  { id: 'dist-bhopal', stateId: 'state-mp', name: 'Bhopal', code: 'BP', lgdCode: 418 },
  { id: 'dist-khordha', stateId: 'state-od', name: 'Khordha', code: 'KH', lgdCode: 374 },
];

export const SEED_VILLAGES = [
  { id: 'vil-padra', districtId: 'dist-vadodara', name: 'Padra Village', lgdCode: 51201 },
  { id: 'vil-karjan', districtId: 'dist-vadodara', name: 'Karjan Gram', lgdCode: 51202 },
  { id: 'vil-haveli', districtId: 'dist-pune', name: 'Haveli Tehsil Village', lgdCode: 52201 },
  { id: 'vil-amber', districtId: 'dist-jaipur', name: 'Amber Rural', lgdCode: 10401 },
  { id: 'vil-bakshi', districtId: 'dist-lucknow', name: 'Bakshi Ka Talab', lgdCode: 15701 },
  { id: 'vil-kolar', districtId: 'dist-bhopal', name: 'Kolar Suburb', lgdCode: 41801 },
];

export const SEED_ROLES = [
  { id: 'role-super-admin', code: 'SUPER_ADMIN', name: 'Super Administrator', description: 'National system administrator' },
  { id: 'role-district-collector', code: 'DISTRICT_COLLECTOR', name: 'District Collector / DM', description: 'Head of District Land Acquisition' },
  { id: 'role-cala', code: 'CALA', name: 'Competent Authority (CALA)', description: 'Competent Authority for Land Acquisition under NHAI/Railways' },
  { id: 'role-state-nodal', code: 'STATE_NODAL_OFFICER', name: 'State Nodal Officer', description: 'State Revenue Department Oversight' },
  { id: 'role-joint-sec', code: 'JOINT_SECRETARY', name: 'Joint Secretary (DoLR)', description: 'Central Ministry Executive Monitoring' },
  { id: 'role-tehsildar', code: 'TEHSILDAR', name: 'Tehsildar / SDO', description: 'Sub-Divisional Land Officer' },
  { id: 'role-comp-officer', code: 'COMPENSATION_OFFICER', name: 'Compensation Officer', description: 'Valuation & Award Disbursal Officer' },
  { id: 'role-rr-officer', code: 'RR_OFFICER', name: 'R&R Officer', description: 'Rehabilitation & Resettlement Administrator' },
  { id: 'role-field-officer', code: 'FIELD_OFFICER', name: 'Field Survey Officer', description: 'On-site cadastral inspection & GPS verification' },
];

// Pre-computed bcrypt hash for password "Bhumitra@2026"
// Generated via bcrypt.hashSync("Bhumitra@2026", 10)
export const SEED_PASSWORD_HASH = '$2a$10$Qj/NfX.6rLzZp6Ew0Yp0E.7Xj8oM7K6z5yL4x3w2v1u0t9s8r7q6p';

export const SEED_USERS = [
  {
    id: 'user-collector-vadodara',
    officerId: 'GJ-DM-VD-0042',
    name: 'Shri Rajesh Sharma, IAS',
    email: 'rajesh.sharma@ias.gov.in',
    designation: 'District Collector / DM (Vadodara)',
    jurisdiction: 'Vadodara District, Gujarat',
    roleId: 'role-district-collector',
    districtId: 'dist-vadodara',
    phone: '+91 98250 12345',
  },
  {
    id: 'user-cala-jaipur',
    officerId: 'RJ-CALA-JP-109',
    name: 'Smt. Priya Meena, RAS',
    email: 'priya.meena@ras.gov.in',
    designation: 'CALA — Competent Authority (NH-48)',
    jurisdiction: 'Jaipur Rural, Rajasthan',
    roleId: 'role-cala',
    districtId: 'dist-jaipur',
    phone: '+91 94140 56789',
  },
  {
    id: 'user-js-mord',
    officerId: 'DL-JS-DOLR-001',
    name: 'Dr. Alok Kumar, IAS',
    email: 'alok.kumar@nic.in',
    designation: 'Joint Secretary (DoLR, New Delhi)',
    jurisdiction: 'National Command, MoRD',
    roleId: 'role-joint-sec',
    phone: '+91 98100 99887',
  },
  {
    id: 'user-sno-maharashtra',
    officerId: 'MH-SNO-REV-204',
    name: 'Shri Sunil Patil, IAS',
    email: 'sunil.patil@mahagov.in',
    designation: 'State Nodal Officer (Revenue)',
    jurisdiction: 'State of Maharashtra',
    roleId: 'role-state-nodal',
    phone: '+91 98200 44332',
  },
  {
    id: 'user-tehsildar-lucknow',
    officerId: 'UP-TEH-LKO-551',
    name: 'Shri Amit Verma',
    email: 'amit.verma@uprevenue.gov.in',
    designation: 'Tehsildar / Revenue Inspector',
    jurisdiction: 'Lucknow Sub-Division, Uttar Pradesh',
    roleId: 'role-tehsildar',
    districtId: 'dist-lucknow',
    phone: '+91 94500 77665',
  },
  {
    id: 'user-admin-national',
    officerId: 'ADMIN-DOLR-00',
    name: 'National Platform Administrator',
    email: 'admin@bhumitra.gov.in',
    designation: 'Chief Technology Officer (DoLR)',
    jurisdiction: 'National Portal',
    roleId: 'role-super-admin',
    phone: '+91 99999 00000',
  },
];

export const SEED_PROJECTS = [
  {
    id: 'proj-0084',
    projectCode: 'DOLR-2026-0084',
    name: 'NH-48 Bharatmala Six-Laning Corridor',
    description: 'Expansion of National Highway 48 corridor from 4 to 6 lanes with grade separators and service roads under Bharatmala Pariyojana Phase 1.',
    type: 'Highway',
    ministry: 'Ministry of Road Transport & Highways (MoRTH)',
    requiringBody: 'National Highways Authority of India (NHAI)',
    stateId: 'state-gj',
    districtId: 'dist-vadodara',
    stage: '05 - Section 15 Objection Hearing Completed',
    stageCode: 'SEC_15_HEARING',
    status: 'IN_PROGRESS',
    totalAreaProposedHa: 142.5,
    totalAreaNotifiedHa: 138.2,
    totalAreaAcquiredHa: 89.4,
    estimatedBudgetCr: 480.0,
    compensationAssessedCr: 148.5,
    compensationDisbursedCr: 98.4,
    affectedFamilies: 112,
    slaDaysRemaining: 8,
    riskLevel: 'high',
    delayPredictedDays: 18,
    recommendedAction: 'Expedite Section 19 declaration to prevent statutory lapse within 8 days',
    targetCompletionDate: new Date('2026-12-31'),
    startDate: new Date('2025-04-01'),
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[73.18, 22.30], [73.22, 22.31], [73.24, 22.28], [73.19, 22.27], [73.18, 22.30]]],
    },
  },
  {
    id: 'proj-0071',
    projectCode: 'DOLR-2026-0071',
    name: 'Eastern Dedicated Freight Corridor',
    description: 'Double-track freight railway corridor facilitating high-capacity heavy haulage from Ludhiana to Dankuni.',
    type: 'Rail',
    ministry: 'Ministry of Railways',
    requiringBody: 'Dedicated Freight Corridor Corporation of India (DFCCIL)',
    stateId: 'state-rj',
    districtId: 'dist-jaipur',
    stage: '04 - Section 19 Acquisition Declaration Published',
    stageCode: 'SEC_19_DECLARATION',
    status: 'IN_PROGRESS',
    totalAreaProposedHa: 310.0,
    totalAreaNotifiedHa: 304.5,
    totalAreaAcquiredHa: 210.8,
    estimatedBudgetCr: 920.0,
    compensationAssessedCr: 284.0,
    compensationDisbursedCr: 210.0,
    affectedFamilies: 245,
    slaDaysRemaining: 24,
    riskLevel: 'medium',
    delayPredictedDays: 7,
    recommendedAction: 'Publish draft Section 23 award schedule for agricultural clusters',
    targetCompletionDate: new Date('2027-06-30'),
    startDate: new Date('2024-10-15'),
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[75.75, 26.90], [75.85, 26.95], [75.90, 26.85], [75.78, 26.80], [75.75, 26.90]]],
    },
  },
  {
    id: 'proj-0066',
    projectCode: 'DOLR-2026-0066',
    name: 'Pune–Nashik Semi High-Speed Rail',
    description: 'Greenfield semi-high-speed rail connectivity reducing transit between Pune and Nashik to 1 hour 45 minutes.',
    type: 'Rail',
    ministry: 'Ministry of Railways & Govt of Maharashtra',
    requiringBody: 'Maharashtra Rail Infrastructure Development Corporation (MRIDC)',
    stateId: 'state-mh',
    districtId: 'dist-pune',
    stage: '02 - Section 11 Preliminary Notified',
    stageCode: 'SEC_11_PRELIMINARY',
    status: 'IN_PROGRESS',
    totalAreaProposedHa: 218.7,
    totalAreaNotifiedHa: 218.7,
    totalAreaAcquiredHa: 45.2,
    estimatedBudgetCr: 740.0,
    compensationAssessedCr: 198.0,
    compensationDisbursedCr: 45.0,
    affectedFamilies: 178,
    slaDaysRemaining: 45,
    riskLevel: 'low',
    delayPredictedDays: 0,
    recommendedAction: 'Schedule hearing dates for Haveli and Shirur public objections',
    targetCompletionDate: new Date('2027-12-31'),
    startDate: new Date('2025-01-10'),
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[73.80, 18.52], [73.92, 18.60], [73.95, 18.48], [73.82, 18.45], [73.80, 18.52]]],
    },
  },
  {
    id: 'proj-0059',
    projectCode: 'DOLR-2026-0059',
    name: 'Lucknow Metro Phase III North Corridor',
    description: 'Transit metro corridor extension serving high-density urban nodes in Greater Lucknow sub-divisions.',
    type: 'Metro',
    ministry: 'Ministry of Housing & Urban Affairs (MoHUA)',
    requiringBody: 'Uttar Pradesh Metro Rail Corporation (UPMRC)',
    stateId: 'state-up',
    districtId: 'dist-lucknow',
    stage: '06 - Compensation Assessment & Awards',
    stageCode: 'VALUATION',
    status: 'DELAYED',
    totalAreaProposedHa: 64.2,
    totalAreaNotifiedHa: 64.2,
    totalAreaAcquiredHa: 38.0,
    estimatedBudgetCr: 310.0,
    compensationAssessedCr: 142.0,
    compensationDisbursedCr: 78.5,
    affectedFamilies: 84,
    slaDaysRemaining: -3,
    riskLevel: 'critical',
    delayPredictedDays: 35,
    recommendedAction: 'Release frozen DBT mandates for 12 commercial awardees with verified bank accounts',
    targetCompletionDate: new Date('2026-09-30'),
    startDate: new Date('2024-03-01'),
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[80.90, 26.82], [80.98, 26.88], [81.02, 26.80], [80.92, 26.78], [80.90, 26.82]]],
    },
  },
  {
    id: 'proj-0048',
    projectCode: 'DOLR-2026-0048',
    name: 'Bhopal Smart City Western Ring Road',
    description: 'Peripheral arterial bypass reducing urban congestion around Bhopal metropolitan region.',
    type: 'Smart City',
    ministry: 'Ministry of Housing & Urban Affairs',
    requiringBody: 'Madhya Pradesh Road Development Corporation (MPRDC)',
    stateId: 'state-mp',
    districtId: 'dist-bhopal',
    stage: '07 - Section 23 Award Declaration',
    stageCode: 'SEC_23_AWARD',
    status: 'IN_PROGRESS',
    totalAreaProposedHa: 95.8,
    totalAreaNotifiedHa: 95.8,
    totalAreaAcquiredHa: 76.5,
    estimatedBudgetCr: 260.0,
    compensationAssessedCr: 98.2,
    compensationDisbursedCr: 88.0,
    affectedFamilies: 92,
    slaDaysRemaining: 32,
    riskLevel: 'low',
    delayPredictedDays: 0,
    recommendedAction: 'Initiate Section 38 possession proceedings for compensated parcels',
    targetCompletionDate: new Date('2026-11-15'),
    startDate: new Date('2024-06-20'),
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[77.38, 23.22], [77.46, 23.27], [77.49, 23.18], [77.40, 23.16], [77.38, 23.22]]],
    },
  },
  {
    id: 'proj-0041',
    projectCode: 'DOLR-2026-0041',
    name: 'Amritsar Smart City Heritage Corridor',
    description: 'Dedicated tourism transit and road widening linking Golden Temple access corridors.',
    type: 'Smart City',
    ministry: 'Ministry of Tourism & Urban Affairs',
    requiringBody: 'Amritsar Smart City Corporation Limited',
    stateId: 'state-gj', // Linked for prototype demonstration
    districtId: 'dist-vadodara',
    stage: '05 - Section 15 Hearing Completed',
    stageCode: 'SEC_15_HEARING',
    status: 'IN_PROGRESS',
    totalAreaProposedHa: 51.3,
    totalAreaNotifiedHa: 51.3,
    totalAreaAcquiredHa: 32.1,
    estimatedBudgetCr: 190.0,
    compensationAssessedCr: 72.0,
    compensationDisbursedCr: 54.0,
    affectedFamilies: 46,
    slaDaysRemaining: 12,
    riskLevel: 'medium',
    delayPredictedDays: 4,
    recommendedAction: 'Finalize compensation apportionment for commercial tenants',
    targetCompletionDate: new Date('2026-10-31'),
    startDate: new Date('2024-11-01'),
  },
];

export const SEED_PARCELS = [
  {
    id: 'parcel-103-10',
    parcelNumber: '103-10',
    surveyNo: '103/10',
    projectId: 'proj-0084',
    stateId: 'state-gj',
    districtId: 'dist-vadodara',
    villageId: 'vil-padra',
    totalAreaHa: 1.42,
    acquiredAreaHa: 0.95,
    landCategory: 'Agricultural (Irrigated)',
    landUse: 'Double Crop Cotton & Wheat',
    stage: '05 - Section 15 Objection Hearing Completed',
    stageCode: 'SEC_15_HEARING',
    compensationStatus: 'Partially Paid (80%)',
    compensationAssessed: '₹48.50 Lakhs (incl. 100% Solatium & Multiplier)',
    compensationAssessedAmount: 4850000,
    rrStatus: 'Eligible: Resettlement Plot #24 Allocated',
    possessionStatus: 'Pending Compensation',
    coordinates: '22°18\'42.1"N, 73°11\'24.8"E',
    latitude: 22.311694,
    longitude: 73.190222,
    gazetteNotice: 'Gazette Extra. No. 512/2026-DoLR',
    color: '#F59E0B',
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[73.1901, 22.3115], [73.1908, 22.3118], [73.1906, 22.3125], [73.1898, 22.3122], [73.1901, 22.3115]]],
    },
    owners: [
      { name: 'Shri Ramchandra Patil', sharePercentage: 60, bankAccountVerified: true, isMainOwner: true, phone: '+91 98251 44556' },
      { name: 'Smt. Shobhaben Patil', sharePercentage: 20, bankAccountVerified: true, isMainOwner: false },
      { name: 'Shri Dinesh Patil', sharePercentage: 20, bankAccountVerified: false, isMainOwner: false },
    ],
  },
  {
    id: 'parcel-102-1A',
    parcelNumber: '102-1A',
    surveyNo: '102/1A',
    projectId: 'proj-0084',
    stateId: 'state-gj',
    districtId: 'dist-vadodara',
    villageId: 'vil-padra',
    totalAreaHa: 0.88,
    acquiredAreaHa: 0.88,
    landCategory: 'Agricultural (Dry Crop)',
    landUse: 'Single Crop Millet',
    stage: '04 - Section 11(1) Preliminary Notified',
    stageCode: 'SEC_11_PRELIMINARY',
    compensationStatus: 'Hearing Pending',
    compensationAssessed: '₹32.40 Lakhs (Draft Estimate)',
    compensationAssessedAmount: 3240000,
    rrStatus: 'Alternative Housing Subsistence Grant Applied',
    possessionStatus: 'Pending Compensation',
    coordinates: '22°18\'45.6"N, 73°11\'29.2"E',
    latitude: 22.312667,
    longitude: 73.191444,
    gazetteNotice: 'Gazette Extra. No. 512/2026-DoLR',
    color: '#EF4444',
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[73.1912, 22.3124], [73.1918, 22.3127], [73.1916, 22.3132], [73.1909, 22.3129], [73.1912, 22.3124]]],
    },
    owners: [
      { name: 'Smt. Kamlaben Rathod', sharePercentage: 100, bankAccountVerified: true, isMainOwner: true, phone: '+91 98252 66778' },
    ],
  },
  {
    id: 'parcel-104-B',
    parcelNumber: '104-B',
    surveyNo: '104/B',
    projectId: 'proj-0084',
    stateId: 'state-gj',
    districtId: 'dist-vadodara',
    villageId: 'vil-karjan',
    totalAreaHa: 2.10,
    acquiredAreaHa: 1.15,
    landCategory: 'Agricultural (Irrigated)',
    landUse: 'Orchard & Tube Well Irrigated Farm',
    stage: '06 - Compensation Disbursed (Direct Transfer)',
    stageCode: 'COMPENSATION_DISBURSED',
    compensationStatus: 'Disbursed (100%)',
    compensationAssessed: '₹76.80 Lakhs (Assets Valued)',
    compensationAssessedAmount: 7680000,
    rrStatus: 'Self-Relocation Grant Sanctioned',
    possessionStatus: 'Handover Scheduled',
    coordinates: '22°18\'39.4"N, 73°11\'21.3"E',
    latitude: 22.310944,
    longitude: 73.189250,
    gazetteNotice: 'Gazette Extra. No. 512/2026-DoLR',
    color: '#3B82F6',
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[73.1890, 22.3107], [73.1898, 22.3111], [73.1895, 22.3117], [73.1887, 22.3113], [73.1890, 22.3107]]],
    },
    owners: [
      { name: 'Shri Govindbhai Solanki', sharePercentage: 100, bankAccountVerified: true, isMainOwner: true, phone: '+91 98253 88990' },
    ],
  },
  {
    id: 'parcel-105-C',
    parcelNumber: '105-C',
    surveyNo: '105/C',
    projectId: 'proj-0084',
    stateId: 'state-gj',
    districtId: 'dist-vadodara',
    villageId: 'vil-karjan',
    totalAreaHa: 4.60,
    acquiredAreaHa: 2.40,
    landCategory: 'Community Gauchar',
    landUse: 'Gram Panchayat Common Grazing Land',
    stage: '08 - Section 38 Possession Completed',
    stageCode: 'SEC_38_POSSESSION',
    compensationStatus: 'Disbursed (100%)',
    compensationAssessed: '₹112.00 Lakhs (Panchayat Escrow)',
    compensationAssessedAmount: 11200000,
    rrStatus: 'Compensatory Grazing Land Allotted in Village 043',
    possessionStatus: 'Possession Taken',
    coordinates: '22°18\'35.0"N, 73°11\'15.0"E',
    latitude: 22.309722,
    longitude: 73.187500,
    gazetteNotice: 'Gazette Extra. No. 512/2026-DoLR',
    color: '#10B981',
    boundaryGeoJson: {
      type: 'Polygon',
      coordinates: [[[73.1872, 22.3095], [73.1882, 22.3100], [73.1879, 22.3108], [73.1869, 22.3103], [73.1872, 22.3095]]],
    },
    owners: [
      { name: 'Gram Panchayat Karjan Common Body', sharePercentage: 100, bankAccountVerified: true, isMainOwner: true },
    ],
  },
];

export const SEED_PRIORITY_ACTIONS = [
  {
    id: 'act-001',
    projectId: 'proj-0084',
    projectName: 'NH-48 Bharatmala Six-Laning',
    title: 'SLA Breach — Section 19 Declaration Imminent',
    description: 'NH-48, Lucknow Metro, DFC Phase II overdue for statutory Section 19 notification filing within 12 months.',
    actionType: 'SLA_BREACH_RESOLUTION',
    priority: 'critical' as const,
    assignedRole: 'CALA',
    dueDate: new Date(Date.now() - 2 * 86400000), // 2 days ago
    daysPending: 14,
    daysOverdue: 2,
    isOverdue: true,
    status: 'ESCALATED',
    escalationLevel: 2,
  },
  {
    id: 'act-002',
    projectId: 'proj-0084',
    projectName: 'NH-48 Bharatmala Six-Laning',
    title: 'Gazette Response Pending',
    description: 'CALA objection disposal summary not filed for 7 affected khatedars in Vadodara sub-division.',
    actionType: 'GAZETTE_RESPONSE',
    priority: 'critical' as const,
    assignedRole: 'DISTRICT_COLLECTOR',
    dueDate: new Date(Date.now() - 1 * 86400000),
    daysPending: 9,
    daysOverdue: 1,
    isOverdue: true,
    status: 'PENDING',
    escalationLevel: 1,
  },
  {
    id: 'act-003',
    projectId: 'proj-0059',
    projectName: 'Lucknow Metro Phase III',
    title: 'Disbursal Mandate Hold — Bank Verification',
    description: 'Beneficiary account verification pending in 12 awardee cases in Lucknow North Corridor.',
    actionType: 'DISBURSAL_MANDATE_HOLD',
    priority: 'high' as const,
    assignedRole: 'COMPENSATION_OFFICER',
    dueDate: new Date(Date.now() + 1 * 86400000),
    daysPending: 4,
    daysOverdue: 0,
    isOverdue: false,
    status: 'IN_PROGRESS',
    escalationLevel: 0,
  },
  {
    id: 'act-004',
    projectId: 'proj-0084',
    projectName: 'NH-48 Bharatmala Six-Laning',
    title: 'Section 15 Hearing Scheduled Today',
    description: 'Section 15 public objection hearing — Gujarat Vadodara & Bharuch clusters.',
    actionType: 'OBJECTION_HEARING',
    priority: 'high' as const,
    assignedRole: 'DISTRICT_COLLECTOR',
    dueDate: new Date(Date.now() + 86400000),
    daysPending: 1,
    daysOverdue: 0,
    isOverdue: false,
    status: 'IN_PROGRESS',
    escalationLevel: 0,
  },
  {
    id: 'act-005',
    projectId: 'proj-0066',
    projectName: 'Pune–Nashik Semi High-Speed Rail',
    title: 'Forest Clearance & Environment Clearance Required',
    description: 'MoEF & CC pending approval for 18.2 Ha notified forest land parcels in Western Ghats corridor.',
    actionType: 'ENV_CLEARANCE',
    priority: 'medium' as const,
    assignedRole: 'STATE_NODAL_OFFICER',
    dueDate: new Date(Date.now() + 5 * 86400000),
    daysPending: 12,
    daysOverdue: 0,
    isOverdue: false,
    status: 'PENDING',
    escalationLevel: 0,
  },
];

export const SEED_GRIEVANCES = [
  {
    id: 'grv-0038',
    ticketNumber: 'GRV-2026-0038',
    projectId: 'proj-0084',
    parcelId: 'parcel-103-10',
    complainantName: 'Shri Ramchandra Patil',
    phone: '+91 98251 44556',
    category: 'COMPENSATION_DISPUTE',
    description: 'Claiming commercial multiplier factor of 1.5 instead of 1.0 due to adjacent National Highway front corridor frontage.',
    filingDate: new Date('2026-08-15'),
    hearingDate: new Date('2026-09-12'),
    slaDueDate: new Date('2026-09-15'),
    isOverdue: false,
    assignedOfficerName: 'Shri Rajesh Sharma, IAS',
    status: 'HEARING_SCHEDULED',
  },
  {
    id: 'grv-0042',
    ticketNumber: 'GRV-2026-0042',
    projectId: 'proj-0084',
    parcelId: 'parcel-102-1A',
    complainantName: 'Smt. Kamlaben Rathod',
    phone: '+91 98252 66778',
    category: 'R_AND_R_DENIAL',
    description: 'Requesting entitlement for alternative dwelling under RFCTLARR Second Schedule due to complete residential parcel acquisition.',
    filingDate: new Date('2026-08-20'),
    slaDueDate: new Date('2026-09-20'),
    isOverdue: false,
    assignedOfficerName: 'Shri Rajesh Sharma, IAS',
    status: 'UNDER_INVESTIGATION',
  },
];
